all:
	g++ PipelinedMIPSProcessor.cpp -lreadline

testcase1:
	./a.out testcase1.txt

testcase2:
	./a.out testcase2.txt

testcase3:
	./a.out testcase3.txt

testcase4:
	./a.out testcase4.txt

testcase5:
	./a.out testcase5.txt

testcase6:
	./a.out testcase6.txt

clean:
	rm -r a.out