all:
	g++ PipelinedMIPSProcessor.cpp -lreadline

testcase1a:
	./a.out testcase1.txt 0.35 3

testcase1b:
	./a.out testcase1.txt 0.65 3

testcase1c:
	./a.out testcase1.txt 0.95 3

testcase2a:
	./a.out testcase2.txt 0.35 3

testcase2b:
	./a.out testcase2.txt 0.65 3

testcase2c:
	./a.out testcase2.txt 0.95 3

testcase3a:
	./a.out testcase3.txt 0.35 3

testcase3b:
	./a.out testcase3.txt 0.65 3

testcase3c:
	./a.out testcase3.txt 0.95 3

testcase4a:
	./a.out testcase4.txt 0.35 3

testcase4b:
	./a.out testcase4.txt 0.65 3

testcase4c:
	./a.out testcase4.txt 0.95 3

testcase5a:
	./a.out testcase5.txt 0.35 3

testcase5b:
	./a.out testcase5.txt 0.65 3

testcase5c:
	./a.out testcase5.txt 0.95 3

testcase6a:
	./a.out testcase6.txt 0.35 3

testcase6b:
	./a.out testcase6.txt 0.65 3

testcase6c:
	./a.out testcase6.txt 0.95 3

clean:
	rm -r a.out